GET http://localhost:3000/words/


###

POST http://localhost:3000/words
Content-Type: application/json

    { 
    "word": "exuberance",
    "definition": "the quality of being full of energy, excitement, and cheerfulness; ebullience.",
    "plural": "exuberances",
    "word_type": "noun",
    "example": "a sense of youthful exuberance",
    "synonyms": ["ebullience", "buoyancy", "cheerfulness", "euphoria", "gaiety", "jubilation"]
    }
###
DELETE http://localhost:3000/words/605e1ad2b1eed6146c799397

###
PUT  http://localhost:3000/words/605e1ed6b1eed6146c7993a0
Content-Type: application/json

{

            "word_type": "noun"
}
###
PUT http://localhost:3000/words/newmeaning/605e075b603cda0f60b2dd05
Content-Type: application/json


                    "definition": "weak beer",
                    "example": "a pickle of hear